version: "3.5"

services:
  db:
    container_name: monorepo-web-api-db
    environment:
      POSTGRES_DB: "${WEB_API_POSTGRES_DB}"
      POSTGRES_PASSWORD: "${WEB_API_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${WEB_API_POSTGRES_USER}"
    hostname: postgres
    image: "postgres:12.2"
    ports:
      - "$WEB_API_POSTGRES_PORT:5432"
    restart: 'always'
    volumes:
      - monorepo-web-api-db-admin:/root/.pgadmin:cached
  db-admin:
    container_name: monorepo-web-api-db-admin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "${GLOBAL_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${GLOBAL_PGADMIN_DEFAULT_PASSWORD}"
    image: "dpage/pgadmin4"
    logging:
      driver: "none"
    ports:
      - "5000:80"
    volumes:
      - monorepo-web-api-db-admin:/root/.pgadmin:cached
  db-e2e:
    container_name: monorepo-web-api-db-e2e
    environment:
      POSTGRES_DB: "${WEB_API_POSTGRES_DB}"
      POSTGRES_PASSWORD: "${WEB_API_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${WEB_API_POSTGRES_USER}"
    hostname: postgres
    image: "postgres:12.2"
    ports:
      - "$WEB_API_POSTGRES_PORT_E2E:5432"
    restart: 'always'
    volumes:
      - monorepo-web-api-db-e2e:/root/.pgadmin:cached
volumes:
  monorepo-web-api-db:
  monorepo-web-api-db-admin:
  monorepo-web-api-db-e2e:

